<a href="https://colab.research.google.com/github/souparnabose99/latent-dirichlet-allocation/blob/main/Latent_Dirichlet_Allocation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load Dataset & Libraries:

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('npr.csv')
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [3]:
df.shape

(11992, 1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11992 entries, 0 to 11991
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Article  11992 non-null  object
dtypes: object(1)
memory usage: 93.8+ KB


In [5]:
df.describe()

Article
count                                               11992
unique                                              11991
top     Washington state has released an estimated 3, ...
freq                                                    2

In [6]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

### Perform Text Preprocessing:

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english')

In [9]:
doc_term_mat = cv.fit_transform(df['Article'])
doc_term_mat

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

### Perform Latent Dirchlet Allocation:

In [10]:
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=7, random_state=42)

In [11]:
lda.fit(doc_term_mat)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

### Grab vocabulary of words:

In [12]:
print(len(cv.get_feature_names()))
print(type(cv.get_feature_names()))

54777
<class 'list'>


In [13]:
import random

for i in range(10):
  random_word_id = random.randint(0,54777)
  print(cv.get_feature_names()[random_word_id])

strongman
hussain
limit
apocryphal
infinitum
emiliano
stoned
surpluses
massacred
cobain


### Grab topics:

In [15]:
print(len(lda.components_))
print(type(lda.components_))
print(lda.components_.shape)

7
<class 'numpy.ndarray'>
(7, 54777)


In [16]:
arr = np.array([10, 100, 1])
print(arr)
print(arr.argsort())

[ 10 100   1]
[2 0 1]


In [17]:
single_topic = lda.components_[0]
single_topic

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [18]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [19]:
# Top 10 values:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [21]:
top_thirty_words = single_topic.argsort()[-30:]

for index in top_thirty_words:
  print(cv.get_feature_names()[index])

jobs
workers
administration
years
according
law
plan
states
business
pay
president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


### Grab highest probabilty words per topic:

In [24]:
for i, topic in enumerate(lda.components_):
  print(f"The Top 15 words for Topic : {i+1}")
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  print('\n')

The Top 15 words for Topic : 1
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


The Top 15 words for Topic : 2
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


The Top 15 words for Topic : 3
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


The Top 15 words for Topic : 4
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


The Top 15 words for Topic : 5
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


The Top 15 words for Topic : 6
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 't

In [25]:
doc_term_mat

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [27]:
df.head(10)

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...
5  I did not want to join yoga class. I hated tho...
6  With a   who has publicly supported the debunk...
7  I was standing by the airport exit, debating w...
8  If movies were trying to be more realistic, pe...
9  Eighteen years ago, on New Year’s Eve, David F...

### Assigning Topic labels:

In [28]:
topic_results = lda.transform(doc_term_mat)
topic_results.shape

(11992, 7)

In [30]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [31]:
topic_results[0].argmax()

1

In [33]:
df["Topic"] = topic_results.argmax(axis=1)
df.head(20)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      1
4   From photography, illustration and video, to d...      2
5   I did not want to join yoga class. I hated tho...      3
6   With a   who has publicly supported the debunk...      3
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      3
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      2
14  Being overweight can raise your blood pressure...      3
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      2
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1